site_url: https://www.renqvistsverkstad.se
backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
locale: sv
collections:
  - name: pages
    label: Fasta sidor
    files:
      - label: Startsida
        name: startpage
        file: content/pages/startpage.md
        fields:
          - { label: Före rubrik, name: preTitle, widget: string }
          - { label: Rubrik, name: title, widget: string }
          - { label: Efter rubrik, name: postTitle, widget: string }
          - { label: Affisch, name: poster, widget: image, required: false }
      - label: Program
        name: program
        file: content/pages/program.md
        fields:
          - { label: Rubrik, name: title, widget: string }
          - label: Sektioner
            name: sections
            widget: list
            fields:
              - { label: Rubrik, name: title, widget: string, required: false }
              - { label: Text, name: body, widget: markdown }
              - { label: Bild, name: image, widget: image, required: false }
      - label: Om oss
        name: about
        file: content/pages/about.md
        fields:
          - { label: Rubrik, name: title, widget: string }
          - label: Sektioner
            name: sections
            widget: list
            fields:
              - { label: Rubrik, name: title, widget: string, required: false }
              - { label: Text, name: body, widget: markdown }
              - { label: Bild, name: image, widget: image, required: false }
      - label: Kontakt
        name: contact
        file: content/pages/contact.md
        fields:
          - { label: Rubrik, name: title, widget: string }
          - { label: Text, name: text, widget: markdown }
          - { label: Karta, name: map, widget: image }
      - label: Skulpturskogen Ed
        name: skogen
        file: content/pages/skogen.md
        fields:
          - { label: Rubrik, name: title, widget: string }
          - label: Kort
            name: cards
            widget: list
            fields:
              - { label: Rubrik, name: title, widget: string, required: false }
              - { label: Ingress, name: ingress, widget: string, required: false }
              - { label: Text, name: body, widget: markdown }
  - name: exhibitions
    label: Utställningar
    folder: content/exhibitions
    create: true
    fields:
      - { label: Titel, name: title, widget: string }
      - { label: Ordning, name: order, widget: number }
      - {
          label: Youtubefilm,
          name: youtubeUrl,
          widget: string,
          required: false,
        }
      - label: Sektioner
        name: sections
        widget: list
        fields:
          - { label: Rubrik, name: title, widget: string, required: false }
          - { label: Text, name: body, widget: markdown }
          - { label: Bild, name: image, widget: image, required: false }
  
