site_url: https://quirky-brahmagupta-52c82c.netlify.com
backend:
  name: git-gateway
  branch: master
media_folder: static/img
collections:
  - name: pages
    label: Page
    files:
      - label: Startsida
        name: startpage
        file: content/pages/startpage.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Text, name: body, widget: markdown }
          - label: Images
            name: images
            widget: list
            field: { label: Image, name: image, widget: image }
      ´