site_url: https://quirky-brahmagupta-52c82c.netlify.com
backend:
  name: git-gateway
  branch: master
media_folder: public/images/uploads
public_folder: /images/uploads
collections:
  - name: pages
    label: Sidor
    files:
      - label: Startsida
        name: startpage
        file: content/pages/startpage.md
        fields:
          - { label: Före rubrik, name: preTitle, widget: string }
          - { label: Rubrik, name: title, widget: string }
          - { label: Efter rubrik, name: postTitle, widget: string }
          - { label: Affisch, name: poster, widget: image }
      - label: Program
        name: Program
        file: content/pages/program.md
        fields:
          - { label: Rubrik, name: title, widget: string }
